apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  labels:
    io.kompose.service: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}