apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    io.kompose.service: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: 9090
      protocol: TCP
  selector:
    io.kompose.service: prometheus

